go_team/games/urls.py
from django.urls import path

from games.views import game_list, game_create, game_detail, game_update, game_delete, \
    game_join, game_leave

app_name = 'games'

urlpatterns = [
    path("", game_list, name="game_list"),
    path("create/", game_create, name="game_create"),
    path("<int:pk>/", game_detail, name="game_detail"),
    path("<int:pk>/edit/", game_update, name="game_edit"),
    path("<int:pk>/delete/", game_delete, name="game_delete"),
    path("<int:pk>/join/", game_join, name="game_join"),
    path("<int:pk>/leave/", game_leave, name="game_leave"),
]

go_team/go_team/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.urls import path, include
from django.views.generic import CreateView

from user.views import home_view

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path(
        "accounts/register/",
        CreateView.as_view(
            template_name="registration/register.html",
            form_class=UserCreationForm,
            success_url="/",
        ),
        name="register",
    ),
    path("admin/", admin.site.urls),
    path("user/", include("user.urls")),
    path("api/", include("user.api.urls")),
    path("games/", include("games.urls")),
    path("api/", include("games.api.urls")),
    path("", home_view, name="home"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

go_team/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("profile/", views.profile_view, name="profile"),
    path("profile/edit/", views.profile_edit_view, name="profile_edit"),
]

go_team/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}GoTeam{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
    <div id="header">
      <a href="/" class="logo">GoTeam</a>
      <ul class="menu">
        {% if request.user.is_authenticated %}
          <li><a href="{% url 'profile' %}">Профиль</a></li>
          <li>
            <form method="post" action="{% url 'logout' %}" style="display: inline;">
                {% csrf_token %}
                <button type="submit" style="background: none; border: none; color: #FFFFFF; cursor: pointer; padding: 0;">
                    Выйти
                </button>
            </form>
          </li>
        {% else %}
          <li><a href="{% url 'login' %}">Войти</a></li>
        {% endif %}
        {% if not request.user.is_authenticated %}
          <li><a href="{% url 'register' %}">Регистрация</a></li>
        {% endif %}
      </ul>
      {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == 'dashboard' %} class='selected'{% endif %}>
                    <a href="{% url 'home' %}">Главная</a>
                </li>
                <li {% if section == "games" %} class="selected"{% endif %}>
                    <a href="{% url 'games:game_list' %}">Игры</a>
                </li>
            </ul>
        {% endif %}

    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
    <script>
      document.addEventListener('DOMContentLoaded', (event) => {
        // DOM-модель загружена
        {% block domready %}
        {% endblock %}
      })
    </script>
</body>
</html>

go_team/templates/home.html
{% extends "base.html" %}
{% block title %}Главная страница{% endblock %}
{% block content %}
<h1>Добро пожаловать на главную страницу!</h1>
<p>Вы успешно вошли в систему.</p>
{% endblock %}